// @ts-nocheck
import { CallsData } from "@/types/calls";

export const originalData: CallsData = {
  total_rows: "78",
  results: [
    {
      id: 10313753,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 17:40:56",
      date_notime: "2024-09-12",
      time: 0,
      from_number: "791**72**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "Вызов завершен вызывающим абонентом",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "Артур",
      contact_company: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ" Москва',
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10313333,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 17:22:33",
      date_notime: "2024-09-12",
      time: 0,
      from_number: "796**38**",
      from_extension: "",
      to_number: "sip**se**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "Вызов завершен вызывающим абонентом",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10312760,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 16:49:17",
      date_notime: "2024-09-12",
      time: 110,
      from_number: "792**51**",
      from_extension: "",
      to_number: "791**72**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10311641,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 15:50:14",
      date_notime: "2024-09-12",
      time: 0,
      from_number: "797**82**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "781**13**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован", "хуйня"],
      disconnect_reason: "Вызов не получил ответа в течение времени ожидания",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10310850,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 15:14:38",
      date_notime: "2024-09-12",
      time: 0,
      from_number: "798**91**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "781**13**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "Вызов не получил ответа в течение времени ожидания",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10310326,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 14:47:17",
      date_notime: "2024-09-12",
      time: 41,
      from_number: "796**53**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10310248,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 14:40:43",
      date_notime: "2024-09-12",
      time: 152,
      from_number: "796**53**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10308425,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 13:11:38",
      date_notime: "2024-09-12",
      time: 26,
      from_number: "796**21**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "749**20**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "Yandex",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "Александр",
      contact_company: 'ООО "ВИНЛАБ-ЗАПАД"',
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10307086,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 12:17:31",
      date_notime: "2024-09-12",
      time: 29,
      from_number: "798**66**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "Николай",
      contact_company: 'ООО "ВИНЛАБ-РЕГИОН"',
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10305983,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 11:24:40",
      date_notime: "2024-09-12",
      time: 77,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "795**16**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10305217,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 10:54:01",
      date_notime: "2024-09-12",
      time: 7,
      from_number: "792**87**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10305235,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 10:52:52",
      date_notime: "2024-09-12",
      time: 142,
      from_number: "791**83**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "101",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 2726,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10305218,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 10:52:08",
      date_notime: "2024-09-12",
      time: 94,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "792**15**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10304948,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 10:36:43",
      date_notime: "2024-09-12",
      time: 39,
      from_number: "781**40**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10304830,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 10:17:45",
      date_notime: "2024-09-12",
      time: 0,
      from_number: "790**78**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "781**13**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "Вызов не получил ответа в течение времени ожидания",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10304774,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 10:07:13",
      date_notime: "2024-09-12",
      time: 34,
      from_number: "792**06**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "101",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 2726,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10304397,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 09:48:44",
      date_notime: "2024-09-12",
      time: 36,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "781**40**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10304155,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-12 09:31:55",
      date_notime: "2024-09-12",
      time: 0,
      from_number: "796**41**",
      from_extension: "",
      to_number: "sip**se**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "Вызов завершен вызывающим абонентом",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10302758,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 21:07:02",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "793**28**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "Вызов завершен вызывающим абонентом",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10302606,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 18:59:53",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "793**87**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "781**13**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "Вызов не получил ответа в течение времени ожидания",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10302060,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 18:22:26",
      date_notime: "2024-09-11",
      time: 55,
      from_number: "796**21**",
      from_extension: "",
      to_number: "sip**sk**",
      to_extension: "101",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "749**20**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "Yandex",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "Александр",
      contact_company: 'ООО "ВИНЛАБ-ЗАПАД"',
      person_id: 2726,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10299811,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 16:30:26",
      date_notime: "2024-09-11",
      time: 545,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "792**15**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10299582,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 16:27:05",
      date_notime: "2024-09-11",
      time: 161,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**68**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10299181,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 16:09:23",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "798**99**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "Вызов завершен вызывающим абонентом",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10298627,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 15:48:15",
      date_notime: "2024-09-11",
      time: 84,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "793**52**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10298589,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 15:47:31",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**65**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10298383,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 15:41:54",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "781**76**",
      from_extension: "",
      to_number: "sip**se**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "Вызов завершен вызывающим абонентом",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10298133,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 15:30:04",
      date_notime: "2024-09-11",
      time: 55,
      from_number: "792**88**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [
        {
          person_name: "Татьяна",
          person_surname: "Михалкович",
          person_mango_phone: "671",
          duration: "0",
          disconnect_reason: "Получен ответ 'занято' от удаленной стороны",
        },
      ],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10297907,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 15:20:42",
      date_notime: "2024-09-11",
      time: 133,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**88**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10297583,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 15:12:25",
      date_notime: "2024-09-11",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "798**99**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10296386,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 14:24:45",
      date_notime: "2024-09-11",
      time: 49,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "792**07**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10296259,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 14:21:14",
      date_notime: "2024-09-11",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**44**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10296258,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 14:21:02",
      date_notime: "2024-09-11",
      time: 19,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "792**77**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10296257,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 14:20:51",
      date_notime: "2024-09-11",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**59**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295296,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:32:05",
      date_notime: "2024-09-11",
      time: 128,
      from_number: "796**81**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295217,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:31:07",
      date_notime: "2024-09-11",
      time: 1,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**35**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295162,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:30:10",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**28**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295161,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:29:15",
      date_notime: "2024-09-11",
      time: 21,
      from_number: "798**28**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295131,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:28:50",
      date_notime: "2024-09-11",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "798**28**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295130,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:28:34",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**09**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10295129,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:27:10",
      date_notime: "2024-09-11",
      time: 7,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "791**81**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294614,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 13:04:52",
      date_notime: "2024-09-11",
      time: 108,
      from_number: "792**76**",
      from_extension: "",
      to_number: "sip**r_**",
      to_extension: "671",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294333,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:53:09",
      date_notime: "2024-09-11",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**51**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294332,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:50:04",
      date_notime: "2024-09-11",
      time: 107,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "791**08**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294308,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:48:53",
      date_notime: "2024-09-11",
      time: 139,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**60**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294238,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:47:55",
      date_notime: "2024-09-11",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**73**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294196,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:46:55",
      date_notime: "2024-09-11",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**58**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294195,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:46:43",
      date_notime: "2024-09-11",
      time: 6,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "793**28**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294048,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:42:18",
      date_notime: "2024-09-11",
      time: 107,
      from_number: "796**53**",
      from_extension: "",
      to_number: "sip**ha**",
      to_extension: "103",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: ["Скрипт не использован"],
      disconnect_reason: "",
      results: [
        {
          type: "is_new",
          title: "Новый",
          tooltip: "",
        },
      ],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
    {
      id: 10294049,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: 'ООО "ГРУЗЧИКОВ-СЕРВИС СПБ"',
        phone: "74951205096",
      },
      date: "2024-09-11 12:41:31",
      date_notime: "2024-09-11",
      time: 110,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**45**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: "",
    },
  ],
};
